#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Build a Hazelcast OpenShift Operator environment

SYNOPSIS
   $EXECUTABLE [-?]

DESCRIPTION
   Builds a Hazelcast OpenShift Operator environment by downloading all the necessary files and making adjustments
   to the downloaded files. 

DEFAULT:
   ./$EXECUTABLE

EOF
exit
fi

if [ "$(which helm)" == "" ]; then
   echo >&2 "ERROR: The 'helm' executable not found. Command aborted."
   exit 1
fi

#
# Add Hazelcast Helm repo
#
helm repo add hazelcast https://hazelcast-charts.s3.amazonaws.com/
helm repo update
echo ""

#
# Set license key
#
# Set license key

if [[ ${OS_NAME} == DARWIN* ]]; then
   IMDG_LICENSE_KEY_BASE64=$(echo -n "$IMDG_LICENSE_KEY" | base64)
else
   IMDG_LICENSE_KEY_BASE64=$(echo -n "$IMDG_LICENSE_KEY" | base64 -w 0)
fi
sed "s/<base64-hz-license-key>/$IMDG_LICENSE_KEY_BASE64/" "$APP_DIR/etc/hazelcast-enterprise/secret.yaml" > "$APP_DIR/hazelcast/secret.yaml"

#
# Display build information
#
cat <<EOF
The 'secret.yaml' has been generated:

   $APP_DIR/secret.yaml

Apply the secret as follows:

   cd_k8s heml 
   oc apply -f secret.yaml

Build complete.
EOF
