#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Delete all resrouces

SYNOPSIS
   $EXECUTABLE [-oss] [-all] [-?]

DESCRIPTION
   Deletes all but persistent claim resources. To delete persistent claims and 'local-storage'
   specify the '-all' option.

OPTIONS
   -oss
             If specified, then deletes Hazelcast OSS resources, otherwise, Hazelcast Enterprise resources.

   -all
             If specified, then deletes all resources including the persistent claims and 'local-storage'.

EOF
exit
fi

# Delete PadoGrid
./stop_padogrid $@

# Delete Hazelcast
./stop_hazelcast $@

# Delete all routes
echo "Deleting routes..."
oc delete route --all=true

echo ""
echo "Cleanup complete."
