#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Start a Hazelcast using Helm charts

SYNOPSIS
   $EXECUTABLE [-oss] [hazelcast_version] [-?]

DESCRIPTION
   Starts a Hazelcast cluster using Helm charts. The chart reference name is set in the
   'setenv.sh' file as $CHART_REFERENCE_NAME.

OPTIONS
   -oss
             If specified launches Hazelcast OSS, otherwise, Hazelcast Enterprise which requires 
             a license key.

   hazelcast_version
             Hazelcast image version. If unspecified, then the latest Hazelcast image version is
             used.

DEFAULT:
   ./$EXECUTABLE

EXAMPLES:
   # Start the latest Hazelcast OSS 
   ./$EXECUTABLE -oss

   # Start Hazelcast OSS version 4.2.1
   ./$EXECUTABLE -oss 4.2.1

   # Start the latest Hazelcast Enterprise
   ./$EXECUTABLE

   # Start Hazelcast Enterprise 4.2.1
   ./$EXECUTABLE 4.2.1

SEE ALSO
   https://github.com/hazelcast/charts

EOF
exit
fi

if [ "$1" != "" ] && [ "$1" != "-oss" ]; then
   VERSION=$1 
elif [ "$2" != "" ]; then
   VERSION=$2 
else
   VERSION=latest
fi
pushd $APP_DIR/hazelcast > /dev/null
oc apply -f hz-secret.yaml

HELM_OPTS="--values=values.yaml --set image.tag=$VERSION"

if [ -f mc-secret.yaml ]; then
   oc apply -f mc-secret.yaml
   HELM_OPTS="$HELM_OPTS --set mancenter.licenseKeySecretName=mc-license-key-secret"
fi
if [ "$OSS" == "true" ]; then
   helm install $HELM_OPTS \
                --set mancenter.licenseKeySecretName=mc-license-key-secret \
                ${CHART_REFERENCE_NAME} hazelcast/hazelcast
else
   helm install $HELM_OPS \
                --set hazelcast.licenseKeySecretName=hz-license-key-secret \
                ${CHART_REFERENCE_NAME} hazelcast/hazelcast-enterprise
fi
popd > /dev/null
