#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"
PADOGRID_URL=http://padogrid-service-$PROJECT_NAME.apps-crc.testing

if [ "$1" == "-?" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Start padogrid pod

SYNOPSIS
   $EXECUTABLE [storage_class] [-?]

DESCRIPTION
   Launches a PadoGrid pod with the name 'padogrid'. Padogrid keeps workspaces in the
   '/opt/padogrid/workspaces' directory. You can optionally mount that directory to a
   specific storage class. If the storage class is not specified, then the default
   storage class is assigned.

   Execute the following command to list the available storage classes.

      oc get storageclass

   Once a PadoGrid pod is started, you can login to the pod using one of the following
   options.

   - Browser
       URL: $PADOGRID_URL
       Password: padogrid

   - Shell
       ./login_padogrid_pod

   Once logged in, use the 'perf_test' app to ingest data as follows.

      switch_cluster myhz
      create_app
      cd_app perf_test/bin_sh
      ./test_ingestion -run

OPTIONS
   storage_class
             The specified optional storage class is used as the Storage Class for the
             'paodgrid-pvc' Persistent Volume Claim (PVC). If this option is not specified,
             then the default storage class is assigned. If the default storage class
             is not found, then PVC is not created and workspaces will be stored in the
             PadoGrid pod. This may occur for older versions of CRC which lack the default
             storage class.

SEE ALSO
   login_padogrid_pod(1), padogrid/padogrid.yaml, padogrid/padogrid-no-pvc.yaml

EOF
exit
fi

DEFAULT_STORAGE_CLASS_NAME=$(oc get storageclass | grep default | awk '{print $1}')
STORAGE_CLASS_NAME="$1"
if [ "$STORAGE_CLASS_NAME" == "" ]; then
   STORAGE_CLASS_NAME=$DEFAULT_STORAGE_CLASS_NAME
fi

HAZELCAST_SERVICE="$(oc get svc | grep -i ClusterIP | grep 5701 | awk '{ print $1 }')"

if [ "$HAZELCAST_SERVICE" == "" ]; then
  HAZELCAST_SERVICE="$PROJECT_NAME-hazelcast-enterprise"
fi

if [ "$STORAGE_CLASS_NAME" == "" ]; then
  oc process -p HAZELCAST_SERVICE=$HAZELCAST_SERVICE -f $APP_DIR/padogrid/padogrid-no-pvc.yaml -o yaml | oc create -f -
else
  oc process -p HAZELCAST_SERVICE=$HAZELCAST_SERVICE -f $APP_DIR/padogrid/padogrid.yaml -o yaml -p=STORAGE_CLASS_NAME=$STORAGE_CLASS_NAME | oc create -f -
fi

# Expose the PadoGrid service
echo "Exposing PadoGrid JupyterLab service (route)..."
oc expose svc/padogrid-service

cat <<EOF

To login to PadoGrid, use one of the following options.

- Browser
    URL: $PADOGRID_URL
    Password: padogrid

- Shell
    ./login_padogrid_pod

Once logged in, use the 'perf_test' app to ingest data as follows.

   switch_cluster myhz
   create_app
   cd_app perf_test/bin_sh
   ./test_ingestion -run

EOF
