# Security Context properties
securityContext:
  # enabled is a flag to enable Security Context
  enabled: true
  # runAsUser is the user ID used to run the container
  runAsUser: 1000690000
  # runAsGroup is the primary group ID used to run all processes within any container of the pod
  runAsGroup: 1000690000
  # fsGroup is the group ID associated with the container
  fsGroup: 1000690000
