apiVersion: v1
data:
  key: <base64-hz-license-key>
kind: Secret
metadata:
  name: hz-license-key-secret
  labels:
    app.kubernetes.io/name: hazelcast-enterprise
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
